version: '3'

services:
  doctor-service:
    build:
      context: ./doctors
    ports:
      - "8081:8081" 
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ 
    depends_on:
      - mongodb

  appointment-service:
    build:
      context: ./appointments
    ports:
      - "8082:8082" 
    environment:
      - MONGO_URI=mongodb://mongodb:27017/
    depends_on:
      - mongodb

  frontend-service:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - doctor-service
      - appointment-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db 

volumes:
  mongodb_data: 
