version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "3030:3030"  

  appointments:
    build: ./appointments
    ports:
      - "8082:8082" 

  doctors:
    build: ./doctors
    ports:
      - "8081:8081" 

networks:
  default:
    driver: bridge
