version: '3'

services:
  doctors-service:
    build:
      context: ./doctors
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  appointments-service:
    build:
      context: ./appointments
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  frontend-service:
    build:
      context: ./frontend
    ports:
      - "30030:3030"
    depends_on:
      - doctors-service
      - appointments-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
