version: '3.8'

services:
  appointments-service:
    build: ./appointments
    ports:
      - "8082:8082"
    depends_on:
      - mongodb

  doctors-service:
    build: ./doctors
    ports:
      - "8081:8081"
    depends_on:
      - mongodb

  node-service:
    build: ./frontend
    ports:
      - "3030:3030"
    environment:
      - DOCTORS_SERVICE_URL=doctors-service:8081
      - APPOINTMENTS_SERVICE_URL=appointments-service:8082
    depends_on:
      - appointments-service
      - doctors-service

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
