apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      component: frontend
      app: healthcare-ui
  template:
    metadata:
      labels:
        component: frontend
        app: healthcare-ui
    spec:
      containers:
      - name: frontend-ui
        image: shameer6749/frontend-ui-service:v1.0
        env:
        - name: APPOINTMENTS_URL
          value: "http://appointments-service:8082"
        - name: DOCTORS_URL
          value: "http://doctors-service:8081"
        ports:
        - containerPort: 3030
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 3030
          initialDelaySeconds: 10
          periodSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 3030
          initialDelaySeconds: 15
          periodSeconds: 5

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-ui-service
spec:
  selector:
    component: frontend
    app: healthcare-ui
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
  type: LoadBalancer
