apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      tier: frontend
      app: dice
  template:
    metadata:
      labels:
        tier: frontend
        app: dice
    spec:
      containers:
      - name: frontend
        image: shameer6749/frontend-system:latest
        env:
        - name: APPOINTMENTS_URL
          value: appointments:8082
        - name: DOCTORS_URL
          value: doctors:8081
        ports:
        - containerPort: 3030
          name: tcp
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
          requests:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3030
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3030
          initialDelaySeconds: 5
          periodSeconds: 3

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-system
spec:
  selector:
    tier: frontend
    app: dice
  ports:
  - protocol: TCP
    port: 3030
    targetPort: 3030
    nodePort: 31000
  type: NodePort
