apiVersion: apps/v1
kind: Deployment
metadata:
  name: doctors-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: doctors
      app: healthcare-app
  template:
    metadata:
      labels:
        component: doctors
        app: healthcare-app
    spec:
      containers:
      - name: doctors-service
        image: shameer6749/doctors-service:v1
        ports:
        - containerPort: 8081
          name: http
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /healthcheck
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /readiness
            port: 8081
          initialDelaySeconds: 15
          periodSeconds: 5
          successThreshold: 2

---
apiVersion: v1
kind: Service
metadata:
  name: doctors-service
spec:
  selector:
    component: doctors
    app: healthcare-app
  ports:
  - protocol: TCP
    port: 8081
    targetPort: 8081
  type: ClusterIP
