name: CI/CD for Appointments Microservice

on:
  push:
    paths:
      - 'appointments/**'
    branches: 
      - main
  pull_request:
    paths:
      - 'appointments/**'
    branches: 
      - main

jobs:
  docker_build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Docker Setup
      uses: docker/setup-buildx-action@v1

    - name: Docker Hub Login
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker Image Build and Push
      uses: docker/build-push-action@v2
      with:
        file: ./appointments/Dockerfile
        context: ./appointments
        tags: shameer6749/appointments-system:${{ github.sha }}
        push: true

    - name: Modify docker-compose.yaml
      run: |
        sed -i 's/shameer6749\/appointments-system:.*/shameer6749\/appointments-system:${{ github.sha }}/' docker-compose.yaml
      working-directory: ${{ github.workspace }}

    - name: Git Changes Check
      id: changes_check
      run: |
        git diff
        git diff --quiet && echo "::set-output name=changes_detected::false" || echo "::set-output name=changes_detected::true"

    - name: Commit and Push Changes
      if: steps.changes_check.outputs.changes_detected == 'true'
      run: |
        git config --global user.email "shameerabdullah.sa7@gmail.com"
        git config --global user.name "ShameerAbdullah"
        git add docker-compose.yaml
        git commit -m "Automated update of docker-compose.yaml for Appointments Service"
        git push
