name: CI for Appointments Service

on:
  push:
    branches: [ main ]
    paths:
      - 'appointments/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'appointments/**'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./appointments
        file: ./appointments/Dockerfile
        push: true
        tags: yourdockerhubusername/appointments:${{ github.sha }}

    # Optional: Add steps to update docker-compose.yml with the new image tag
    # and push the change back to the repository. This step requires additional
    # scripting and setup.
