name: Doctors Service CI/CD

on:
  push:
    branches: [ main ]
    paths:
      - 'doctors/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'doctors/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./doctors
        file: ./doctors/Dockerfile
        push: true
        tags: shameer6749/doctors-system:${{ github.sha }}

    - name: Update docker-compose.yml
      run: |
        sed -i 's/shameer6749\/doctors-system:.*/shameer6749\/doctors-system:${{ github.sha }}/' docker-compose.yaml
      working-directory: ${{ github.workspace }}
      
    - name: Commit and push if changed
      run: |
        git config --global user.email "shameerabdullah.sa7@gmail.com"
        git config --global user.name "ShameerAbdullah"
        git add docker-compose.yml
        git commit -m "Update docker-compose.yml for doctors"
        git push
