name: CI/CD Pipeline for Doctors Microservice

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'doctors/**'
  push:
    branches: [ main ]
    paths:
      - 'doctors/**'

jobs:
  docker_process:
    runs-on: ubuntu-latest

    steps:
    - name: Clone Repository
      uses: actions/checkout@v2

    - name: Prepare Docker Builder
      uses: docker/setup-buildx-action@v1

    - name: Authenticate Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Docker Build & Push
      uses: docker/build-push-action@v2
      with:
        file: ./doctors/Dockerfile
        context: ./doctors
        tags: shameer6749/doctors-system:${{ github.sha }}
        push: true

    - name: Modify docker-compose.yaml for Doctors
      run: |
        sed -i 's/shameer6749\/doctors-system:.*/shameer6749\/doctors-system:${{ github.sha }}/' docker-compose.yaml
      working-directory: ${{ github.workspace }}

    - name: Verify Git Changes
      id: check_git
      run: |
        git diff
        git diff --quiet && echo "::set-output name=detected_changes::false" || echo "::set-output name=detected_changes::true"

    - name: Push Changes to Repository
      if: steps.check_git.outputs.detected_changes == 'true'
      run: |
        git config --global user.email "shameerabdullah.sa7@gmail.com"
        git config --global user.name "ShameerAbdullah"
        git add docker-compose.yaml
        git commit -m "Automated docker-compose.yaml update for Doctors Service"
        git push
