name: Frontend Microservice Deployment

on:
  pull_request:
    branches: [ main ]
    paths:
      - 'frontend/**'
  push:
    branches: [ main ]
    paths:
      - 'frontend/**'

jobs:
  deployment_process:
    runs-on: ubuntu-latest

    steps:
    - name: Retrieve Code
      uses: actions/checkout@v2

    - name: Docker Environment Setup
      uses: docker/setup-buildx-action@v1

    - name: Docker Hub Authentication
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Building and Pushing Image
      uses: docker/build-push-action@v2
      with:
        file: ./frontend/Dockerfile
        context: ./frontend
        tags: shameer6749/frontend-system:${{ github.sha }}
        push: true

    - name: Update docker-compose.yaml File
      run: |
        sed -i 's/shameer6749\/frontend-system:.*/shameer6749\/frontend-system:${{ github.sha }}/' docker-compose.yaml
      working-directory: ${{ github.workspace }}

    - name: Git Change Detection
      id: detect_changes
      run: |
        git diff
        git diff --quiet && echo "::set-output name=changes_found::false" || echo "::set-output name=changes_found::true"

    - name: Committing and Pushing Changes
      if: steps.detect_changes.outputs.changes_found == 'true'
      run: |
        git config --global user.email "shameerabdullah.sa7@gmail.com"
        git config --global user.name "ShameerAbdullah"
        git add docker-compose.yaml
        git commit -m "Automatic update of docker-compose.yaml for Frontend Service"
        git push
